on:
  push:
    branches: [master]
    # paths:
    #   - "calculator/**"

name: Deploy to Amazon ECS - "calculator"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Build, tag, and push image to Docker Hub
        uses: elgohr/Publish-Docker-Github-Action@2.14
        with:
          workdir: /calculator
          name: ${{ secrets.DOCKER_USERNAME }}/calculator
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: ${{ github.sha }}

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: calculator/task-definition.json
          container-name: onad-calculator
          image: ${{ secrets.DOCKER_USERNAME }}/calculator:${{ github.sha }}

      - name: Deploy Amazon ECS task definition
        uses: airfordable/ecs-deploy-task-definition-to-scheduled-task@v2.0.0
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          cluster: ${{ secrets.AWS_ECS_CLUSTER }}
          wait-for-service-stability: true
