on:
  push:
    branches: [test]
    paths:
      - "tracker/**"

name: <test> Deploy to Amazon ECS - "tracker"

jobs:
  deploy:
    name: Test Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: TS Build
        run: |
          cd tracker
          yarn
          yarn build
          cd -

      - name: Build, tag, and push image to Docker Hub
        uses: elgohr/Publish-Docker-Github-Action@2.14
        with:
          workdir: tracker
          name: ${{ secrets.DOCKER_USERNAME }}/onad_tracker
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "${{ github.sha }},latest"

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: tracker/test-task-definition.json
          container-name: TEST-onad-tracker
          image: ${{ secrets.DOCKER_USERNAME }}/onad_tracker:${{ github.sha }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ secrets.ECS_SERVICE_NAME_TRACKER_TEST }}
          cluster: ${{ secrets.ECS_CLUSTER_NAME_TEST }}
          wait-for-service-stability: true
